# Generated by Django 3.1.7 on 2021-03-27 22:42

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('business_sector', models.CharField(max_length=255)),
                ('employee_count', models.PositiveIntegerField(default=0)),
                ('company_location', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=150)),
                ('contact_job_title', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=200, unique=True)),
                ('contact_telephone', phone_field.models.PhoneField(blank=True, max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_compliance', models.CharField(blank=True, choices=[(3, 'Green'), (2, 'Amber'), (1, 'Red')], default=2, max_length=5, null=True)),
                ('work_n_leaves', models.CharField(blank=True, choices=[(3, 'Green'), (2, 'Amber'), (1, 'Red')], default=2, max_length=5, null=True)),
                ('policies_n_practices', models.CharField(blank=True, choices=[(3, 'Green'), (2, 'Amber'), (1, 'Red')], default=2, max_length=5, null=True)),
                ('employee_reactions', models.CharField(blank=True, choices=[(3, 'Green'), (2, 'Amber'), (1, 'Red')], default=2, max_length=5, null=True)),
                ('training_n_dev', models.CharField(blank=True, choices=[(3, 'Green'), (2, 'Amber'), (1, 'Red')], default=2, max_length=5, null=True)),
                ('recruit_n_retain', models.CharField(blank=True, choices=[(3, 'Green'), (2, 'Amber'), (1, 'Red')], default=2, max_length=5, null=True)),
                ('change_n_reorganise', models.CharField(blank=True, choices=[(3, 'Green'), (2, 'Amber'), (1, 'Red')], default=2, max_length=5, null=True)),
                ('pay_n_benefits', models.CharField(blank=True, choices=[(3, 'Green'), (2, 'Amber'), (1, 'Red')], default=2, max_length=5, null=True)),
                ('employee_communication', models.CharField(blank=True, choices=[(3, 'Green'), (2, 'Amber'), (1, 'Red')], default=2, max_length=5, null=True)),
                ('health_n_safety', models.CharField(blank=True, choices=[(3, 'Green'), (2, 'Amber'), (1, 'Red')], default=2, max_length=5, null=True)),
                ('covid_related', models.CharField(blank=True, choices=[(3, 'Green'), (2, 'Amber'), (1, 'Red')], default=2, max_length=5, null=True)),
                ('records_n_GDPR', models.CharField(blank=True, choices=[(3, 'Green'), (2, 'Amber'), (1, 'Red')], default=2, max_length=5, null=True)),
                ('survey_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey_api.customerinfo')),
            ],
        ),
    ]
