# Generated by Django 3.1.7 on 2021-03-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_api', '0002_auto_20210327_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersurvey',
            name='change_n_reorganise',
            field=models.IntegerField(choices=[(3, 'Green'), (2, 'Amber'), (1, 'Red'), (0, '')], default=0),
        ),
        migrations.AlterField(
            model_name='customersurvey',
            name='covid_related',
            field=models.IntegerField(choices=[(3, 'Green'), (2, 'Amber'), (1, 'Red'), (0, '')], default=0),
        ),
        migrations.AlterField(
            model_name='customersurvey',
            name='employee_communication',
            field=models.IntegerField(choices=[(3, 'Green'), (2, 'Amber'), (1, 'Red'), (0, '')], default=0),
        ),
        migrations.AlterField(
            model_name='customersurvey',
            name='employee_reactions',
            field=models.IntegerField(choices=[(3, 'Green'), (2, 'Amber'), (1, 'Red'), (0, '')], default=0),
        ),
        migrations.AlterField(
            model_name='customersurvey',
            name='health_n_safety',
            field=models.IntegerField(choices=[(3, 'Green'), (2, 'Amber'), (1, 'Red'), (0, '')], default=0),
        ),
        migrations.AlterField(
            model_name='customersurvey',
            name='legal_compliance',
            field=models.IntegerField(choices=[(3, 'Green'), (2, 'Amber'), (1, 'Red'), (0, '')], default=0),
        ),
        migrations.AlterField(
            model_name='customersurvey',
            name='pay_n_benefits',
            field=models.IntegerField(choices=[(3, 'Green'), (2, 'Amber'), (1, 'Red'), (0, '')], default=0),
        ),
        migrations.AlterField(
            model_name='customersurvey',
            name='policies_n_practices',
            field=models.IntegerField(choices=[(3, 'Green'), (2, 'Amber'), (1, 'Red'), (0, '')], default=0),
        ),
        migrations.AlterField(
            model_name='customersurvey',
            name='records_n_GDPR',
            field=models.IntegerField(choices=[(3, 'Green'), (2, 'Amber'), (1, 'Red'), (0, '')], default=0),
        ),
        migrations.AlterField(
            model_name='customersurvey',
            name='recruit_n_retain',
            field=models.IntegerField(choices=[(3, 'Green'), (2, 'Amber'), (1, 'Red'), (0, '')], default=0),
        ),
        migrations.AlterField(
            model_name='customersurvey',
            name='training_n_dev',
            field=models.IntegerField(choices=[(3, 'Green'), (2, 'Amber'), (1, 'Red'), (0, '')], default=0),
        ),
        migrations.AlterField(
            model_name='customersurvey',
            name='work_n_leaves',
            field=models.IntegerField(choices=[(3, 'Green'), (2, 'Amber'), (1, 'Red'), (0, '')], default=0),
        ),
    ]
