# Generated by Django 3.1.7 on 2021-04-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_api', '0003_auto_20210328_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersurvey',
            name='performance_management',
            field=models.IntegerField(choices=[(3, 'Green'), (2, 'Amber'), (1, 'Red'), (0, '')], default=0),
        ),
    ]
