# Generated by Django 3.1.7 on 2021-04-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_api', '0004_customersurvey_performance_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='pdf_report',
            field=models.FileField(blank=True, upload_to='pdf'),
        ),
    ]
